//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.My_Books
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Book.
    /// </summary>
    // *** Start programmer edit section *** (Book CustomAttributes)

    // *** End programmer edit section *** (Book CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("BookE", new string[] {
            "Name as \'Name\'",
            "Author as \'Author\'",
            "Author.Name as \'Name\'"}, Hidden=new string[] {
            "Author.Name"})]
    [AssociatedDetailViewAttribute("BookE", "Tag", "TagE", true, "", "Tag", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("BookE", "Author", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Name")]
    [View("BookL", new string[] {
            "Name as \'Name\'",
            "Author.Name as \'Name\'"})]
    public class Book : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.My_Books.Author fAuthor;
        
        private IIS.My_Books.DetailArrayOfTag fTag;
        
        // *** Start programmer edit section *** (Book CustomMembers)

        // *** End programmer edit section *** (Book CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Book.Name CustomAttributes)

        // *** End programmer edit section *** (Book.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Book.Name Get start)

                // *** End programmer edit section *** (Book.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Book.Name Get end)

                // *** End programmer edit section *** (Book.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Book.Name Set start)

                // *** End programmer edit section *** (Book.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Book.Name Set end)

                // *** End programmer edit section *** (Book.Name Set end)
            }
        }
        
        /// <summary>
        /// Book.
        /// </summary>
        // *** Start programmer edit section *** (Book.Author CustomAttributes)

        // *** End programmer edit section *** (Book.Author CustomAttributes)
        [NotNull()]
        public virtual IIS.My_Books.Author Author
        {
            get
            {
                // *** Start programmer edit section *** (Book.Author Get start)

                // *** End programmer edit section *** (Book.Author Get start)
                IIS.My_Books.Author result = this.fAuthor;
                // *** Start programmer edit section *** (Book.Author Get end)

                // *** End programmer edit section *** (Book.Author Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Book.Author Set start)

                // *** End programmer edit section *** (Book.Author Set start)
                this.fAuthor = value;
                // *** Start programmer edit section *** (Book.Author Set end)

                // *** End programmer edit section *** (Book.Author Set end)
            }
        }
        
        /// <summary>
        /// Book.
        /// </summary>
        // *** Start programmer edit section *** (Book.Tag CustomAttributes)

        // *** End programmer edit section *** (Book.Tag CustomAttributes)
        public virtual IIS.My_Books.DetailArrayOfTag Tag
        {
            get
            {
                // *** Start programmer edit section *** (Book.Tag Get start)

                // *** End programmer edit section *** (Book.Tag Get start)
                if ((this.fTag == null))
                {
                    this.fTag = new IIS.My_Books.DetailArrayOfTag(this);
                }
                IIS.My_Books.DetailArrayOfTag result = this.fTag;
                // *** Start programmer edit section *** (Book.Tag Get end)

                // *** End programmer edit section *** (Book.Tag Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Book.Tag Set start)

                // *** End programmer edit section *** (Book.Tag Set start)
                this.fTag = value;
                // *** Start programmer edit section *** (Book.Tag Set end)

                // *** End programmer edit section *** (Book.Tag Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "BookE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookE", typeof(IIS.My_Books.Book));
                }
            }
            
            /// <summary>
            /// "BookL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View BookL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("BookL", typeof(IIS.My_Books.Book));
                }
            }
        }
    }
}
