//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.My_Books
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Tag.
    /// </summary>
    // *** Start programmer edit section *** (Tag CustomAttributes)

    // *** End programmer edit section *** (Tag CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("TagE", new string[] {
            "Name as \'Name\'"})]
    public class Tag : ICSSoft.STORMNET.DataObject
    {
        
        private string fName;
        
        private IIS.My_Books.Book fBook;
        
        // *** Start programmer edit section *** (Tag CustomMembers)

        // *** End programmer edit section *** (Tag CustomMembers)

        
        /// <summary>
        /// Name.
        /// </summary>
        // *** Start programmer edit section *** (Tag.Name CustomAttributes)

        // *** End programmer edit section *** (Tag.Name CustomAttributes)
        [StrLen(255)]
        public virtual string Name
        {
            get
            {
                // *** Start programmer edit section *** (Tag.Name Get start)

                // *** End programmer edit section *** (Tag.Name Get start)
                string result = this.fName;
                // *** Start programmer edit section *** (Tag.Name Get end)

                // *** End programmer edit section *** (Tag.Name Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Tag.Name Set start)

                // *** End programmer edit section *** (Tag.Name Set start)
                this.fName = value;
                // *** Start programmer edit section *** (Tag.Name Set end)

                // *** End programmer edit section *** (Tag.Name Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.My_Books.Book.
        /// </summary>
        // *** Start programmer edit section *** (Tag.Book CustomAttributes)

        // *** End programmer edit section *** (Tag.Book CustomAttributes)
        [Agregator()]
        [NotNull()]
        public virtual IIS.My_Books.Book Book
        {
            get
            {
                // *** Start programmer edit section *** (Tag.Book Get start)

                // *** End programmer edit section *** (Tag.Book Get start)
                IIS.My_Books.Book result = this.fBook;
                // *** Start programmer edit section *** (Tag.Book Get end)

                // *** End programmer edit section *** (Tag.Book Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Tag.Book Set start)

                // *** End programmer edit section *** (Tag.Book Set start)
                this.fBook = value;
                // *** Start programmer edit section *** (Tag.Book Set end)

                // *** End programmer edit section *** (Tag.Book Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "TagE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View TagE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("TagE", typeof(IIS.My_Books.Tag));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of Tag.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfTag CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfTag CustomAttributes)
    public class DetailArrayOfTag : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.My_Books.DetailArrayOfTag members)

        // *** End programmer edit section *** (IIS.My_Books.DetailArrayOfTag members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type Tag by index.
        /// </summary>
        /// <summary>
        /// Adds object with type Tag.
        /// </summary>
        public DetailArrayOfTag(IIS.My_Books.Book fBook) : 
                base(typeof(Tag), ((ICSSoft.STORMNET.DataObject)(fBook)))
        {
        }
        
        public IIS.My_Books.Tag this[int index]
        {
            get
            {
                return ((IIS.My_Books.Tag)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.My_Books.Tag dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
